remote-url = "git@github.com:hfscheid/ktopology.git"
build-name = "Test Build"
[[phases]]
name = "pre-build"
commands = [
  "echo \"listing project root...\"",
  "ls"
]

[[phases]]
name = "build"
commands = [
  "echo \"attempting to cd into ktgraph...\"",
  "cd ktgraph",
  "echo \"listing ktgraph...\"",
  "ls"
]
