remote-url = "git@github.com:hfscheid/monteiro.git"
build-name = "Test Build"
[[phases]]
name = "pre-build"
commands = [
  "echo \"listing project root...\"",
  "ls"
]

[[phases]]
name = "build"
commands = [
  "echo \"attempting to cd into src...\"",
  "cd src",
  "echo \"listing src...\"",
  "ls"
]
